#!/bin/bash

OPS=(
    simd_add
    simd_sub
    simd_mult
    simd_eq
    simd_ne
    simd_gt
    simd_ugt
    simd_ge
    simd_uge
    simd_lt
    simd_le
    simd_ult
    simd_ule
    simd_max
    simd_min
    simd_umax
    simd_umin
    simd_sllv
    simd_srlv
    simd_rotl
    simd_rotr
    simd_pext
    simd_pdep
    hsimd_packh
    hsimd_packl
    hsimd_packus
    hsimd_packss
    esimd_mergeh
    esimd_mergel
    mvmd_shuffle
    mvmd_shuffle:over
    mvmd_shuffle:highbit
    mvmd_compress
    mvmd_expand
    mvmd_dslli
)
FWS=(32 8 64 1 2 4 16 128)

IDISA_TEST=build-vscode/bin/idisa_exerciser
if [ ! -z "$1" ]; then
    IDISA_TEST="$1"
fi

if [ ! -z "$2" ]; then
    # Don't quote expansion, this way you can say e.g. "simd_add simd_sub" and test multiple specific ops
    OPS=($2)
fi

if [ ! -z "$3" ]; then
    # Don't quote expansion, this way you can say e.g. "2 4" and test multiple specific field widths
    FWS=($3)
fi

CUTLINE=----------------------------------------------------------

echo ${CUTLINE}
echo "--- BEGINNING TESTING PASS"

for OP in ${OPS[@]}; do
    echo ${CUTLINE}
    echo "--- Testing operation ${OP} ---"
    for FW in ${FWS[@]}; do
        OUTBASE="TestOutput/${OP}${FW}"
        ${IDISA_TEST} \
                --ShowIR="${OUTBASE}_test.ll" \
                --ShowASM="${OUTBASE}_test.asm" \
                --output="${OUTBASE}_test.out" \
                $OP $FW TestOutput/vec1 TestOutput/vec2 \
            2>&1 | head -n 500 > "TestOutput/${OP}${FW}.test" &
    done
    wait
    for FW in ${FWS[@]}; do
        echo ${CUTLINE}
        head -n 20 "TestOutput/${OP}${FW}.test"
    done
done

echo ${CUTLINE}
echo "--- BEGINNING TIMING PASS"

for OP in ${OPS[@]}; do
    echo ${CUTLINE}
    echo "Timing operation ${OP}"
    for FW in 4 8 32; do
        OUTBASE="TestOutput/${OP}${FW}"
        echo ${CUTLINE}
        ${IDISA_TEST} --disable-checks --timing \
                --warmup 10 --drop-best 250 --drop-worst 250 --repeat 1000 \
                --ShowIR="${OUTBASE}_time.ll" \
                --ShowASM="${OUTBASE}_time.asm" \
                --output="${OUTBASE}_time.out" \
                $OP $FW TestOutput/vecl1 TestOutput/vecl2 \
            2>&1 > "${OUTBASE}.time"
        head -n 20 "${OUTBASE}.time"
        tail -n 20 "${OUTBASE}.time"
        # different input vectors so this doesn't work
        # diff -q "${OUTBASE}.checkout" "${OUTBASE}.testout"
    done
done
