# Rename this to config.yaml to actually use it

test:
  ir-path:
  asm-path:
  vectors:
  - TestOutput/vec1
  - TestOutput/vec2
  - TestOutput/vec3


timing:
  warmup: 2
  repeat: 1000
  drop-worst: 250
  drop-best: 250
  vectors:
  - TestOutput/vecl1
  - TestOutput/vecl2
  - TestOutput/vecl3

modes:
- name: default
  exerciser-path: build/bin/idisa_exerciser
  block-size: 256
  args:

- name: ssse3
  exerciser-path: build/bin/idisa_exerciser
  block-size: 128
  args: --BlockSize=128

- name: i64
  exerciser-path: build/bin/idisa_exerciser
  block-size: 64
  args: --BlockSize=64
